In [1]:
import numpy as np

1. Create a numpy array with numpy.array module and with a data type integer and float.


In [20]:
#1
a = np.array([1,2,3,4])
b = np.array([0.1,0.2,0.4,0.6])


In [21]:
a.dtype

dtype('int32')

In [22]:
b.dtype

dtype('float64')

In [17]:
#2
arr1 = np.array([1, 2, 3, 4], dtype='int')
arr2 = np.array([1, 2, 3, 4], dtype='float')


In [18]:
arr1.dtype

dtype('int32')

In [19]:
arr2.dtype

dtype('float64')

2. Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
Also, print the shape and dimensions of the numpy arrays created above.

In [34]:
a1 = np.array(1)
a2 = np.array([1,2,3])
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a4 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a5 = np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(np.ndim(a1),np.ndim(a2),np.ndim(a3),np.ndim(a4),np.ndim(a5))
print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a4.shape)
print(a5.shape)


0 1 2 3 4
()
(3,)
(3, 3)
(1, 3, 3)
(1, 1, 3, 3)


3. Create a 2x2, 3x3, and 4x4 identity matrix using numpy.


In [35]:
# 1
a = np.identity(2)
b = np.identity(3)
c = np.identity(4)

print(a)
print(b)
print(c)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
# 2
a = np.identity(2, dtype='int')
b = np.identity(3, dtype='int')
c = np.identity(4, dtype='int')

print(a)
print(b)
print(c)

[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [39]:
# 3
a=np.eye(2, dtype='int')
a

array([[1, 0],
       [0, 1]])

4. Create a numpy array with shape 2x5 that has all the elements as zero

In [42]:
a = np.zeros((2,5))
print(a)
b = np.full((2,5),0)
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]]


5. Create a numpy array that has the shape 3x5 and all the elements are 5.


In [48]:
a=np.full((3,5),5)
print(a)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


6. Create a numpy array with random integers in the range 0-100, and the sample size
should be 25.


In [54]:
a=np.random.randint(0,100,25)
a

array([77, 68,  2, 86, 49, 90, 41, 42, 90, 45, 63, 39,  5, 47,  0, 27,  1,
       53, 93, 91, 51, 96, 24, 57, 63])

In [61]:
len(a)

25

7. Create a numpy array with a shape 3x3 that has all elements as 1.

In [66]:
# 1
a = np.full((3,3),1)
print(a)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [65]:
# 2
b = np.ones((3,3), dtype='int')
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


8. Create a numpy array in the shape 2x3 with random integers in the range 0-100.
Reshape the array in the shape 3x2 and print the updated shape of the resultant array.

In [67]:
a = np.random.randint(0, 100, size=(2,3))
a

array([[24, 22,  3],
       [84, 85, 99]])

In [68]:
a.shape

(2, 3)

In [70]:
a=a.reshape(3,2)

In [71]:
a

array([[24, 22],
       [ 3, 84],
       [85, 99]])

In [72]:
a.shape

(3, 2)

9. Create a random array, with the range 0-1000, with a size 50 and step 2. Perform the
following operations on the same.

a. Print the first ten elements of the array.

b. Print the last ten elements of the array

c. Print the elements from the indexes 10-25

d. Print the element at the index 22

e. Print the array using negative indexing.

f. Print the last ten elements of the array, using negative indexing.


In [73]:
a =np.random.randint(0,1000,50)
print(a)

[892 107 513 168  50 543  80 289 836   4 331 121 616 434 384 950  26 297
 915 459 121 933 674  10 926  75 343  86 480  78  22 267  55 502 797 952
 158 393 545 361 856 944 450  29 207 553 149 682 730 425]


In [74]:
len(a)

50

In [80]:
# a

# a[0:10]
a[:10]

array([892, 107, 513, 168,  50, 543,  80, 289, 836,   4])

In [82]:
# b

# a[40:50]
a[40:]

array([856, 944, 450,  29, 207, 553, 149, 682, 730, 425])

In [83]:
# c

a[10:26]

array([331, 121, 616, 434, 384, 950,  26, 297, 915, 459, 121, 933, 674,
        10, 926,  75])

In [84]:
# d

a[22]

674

In [85]:
# e

a[-50:]

array([892, 107, 513, 168,  50, 543,  80, 289, 836,   4, 331, 121, 616,
       434, 384, 950,  26, 297, 915, 459, 121, 933, 674,  10, 926,  75,
       343,  86, 480,  78,  22, 267,  55, 502, 797, 952, 158, 393, 545,
       361, 856, 944, 450,  29, 207, 553, 149, 682, 730, 425])

In [86]:
# f

a[-10:]

array([856, 944, 450,  29, 207, 553, 149, 682, 730, 425])

In [90]:
# reverse order
a[::-1]


array([425, 730, 682, 149, 553, 207,  29, 450, 944, 856, 361, 545, 393,
       158, 952, 797, 502,  55, 267,  22,  78, 480,  86, 343,  75, 926,
        10, 674, 933, 121, 459, 915, 297,  26, 950, 384, 434, 616, 121,
       331,   4, 836, 289,  80, 543,  50, 168, 513, 107, 892])

10. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.

a. Insert the element 6 at the end of the array.

b. Insert the element 10 at the beginning of the array.

c. Insert the element 30, before 4.

d. Update the element 5 as 50.

e. Delete the element 50 in the updated array.

f. Create a function to search for the element 30.

g. Sort the array in ascending order

In [96]:
a=np.array([1,2,3,4,5])

In [97]:
#a

a=np.append(a,6)
a

array([1, 2, 3, 4, 5, 6])

In [98]:
# b

a=np.insert(a,0,10)
a

array([10,  1,  2,  3,  4,  5,  6])

In [99]:
# c

a=np.insert(a,4,30)
a

array([10,  1,  2,  3, 30,  4,  5,  6])

In [100]:
# d
a[-2]=50
a

array([10,  1,  2,  3, 30,  4, 50,  6])

In [101]:
# e

# np.delete(a,np.where(a==50))

a=np.delete(a,-2)
a

array([10,  1,  2,  3, 30,  4,  6])

In [107]:
l=np.where(a==30)
l

(array([4], dtype=int64),)

In [115]:
# f

# 1
def find(n):
    for i in range(len(a)):
        if a[i]==n:
            print(n,' is present at position ',i)

In [116]:
find(30)

30  is present at position  4


In [117]:
find(1)

1  is present at position  1


In [118]:
find(10)

10  is present at position  0


In [123]:
# 2

def search_element(array, element):
    if element in array:
        return np.where(array == element)
    else:
        return f"The element is not found"
    
index = search_element(a, 30)
print(index[0])


[4]


In [124]:
# g

print(a)
a.sort()
print(a)

[10  1  2  3 30  4  6]
[ 1  2  3  4  6 10 30]


In [133]:
sorted(a, reverse=True)

[30, 10, 6, 4, 3, 2, 1]