# Numpy - numerical python
#### consumes less memory compare to python list
## Hands On

### List - list of elements - [1,'a',['2','b'],3.5,{k:v}]
### Array - list of elements of same data type - [1,2,3,4] - array of integers , ['a','b','c'] - array of strings
### Vector - is a type of array with one dimension


### Basic Array

In [2]:
import numpy as np
np.array([1, 2, 3,4])

array([1, 2, 3, 4])

In [2]:
a = np.array([1, 2, 3,4])
b = np.array([.5, .6, 7,.8])
c=np.array([1,'a',{'k':'v'}])
print(c)

[1 'a' {'k': 'v'}]


In [3]:
a[0], a[1]

(1, 2)

In [4]:
a[0:]

array([1, 2, 3, 4])

In [5]:
a[1:3]

array([2, 3])

In [6]:
a[1:-1]

array([2, 3])

In [7]:
a[::2]

array([1, 3])

### Accessing elements by indexing

In [8]:
b[0], b[1], b[2] #access by index

(0.5, 0.6, 7.0)

In [9]:
b[[0,1,2]] # acccess multiple elements by indexing

array([0.5, 0.6, 7. ])

### Array Types

In [10]:
a

array([1, 2, 3, 4])

In [11]:
a.dtype

dtype('int32')

In [12]:
b.dtype

dtype('float64')

In [3]:
#setting numpy array type
np.array([1, 2, 3,4], dtype=np.float64)

array([1., 2., 3., 4.])

In [14]:
c = np.array(['a','b','c','d'])
c.dtype

dtype('<U1')

In [15]:
d = np.array([{'a':1},sys])
d.dtype

dtype('O')

<h3 style="color:#C5D8A4; background:#534340; border-radius:5px; font">Dimensions and Shapes</h3>

In [12]:
A = np.array([[1,2,3],[4,5,6]])

In [67]:
A.shape

(2, 3)

In [69]:
A.ndim

2

In [70]:
A.size

6

In [13]:
A[:,:2]

array([[1, 2],
       [4, 5]])

In [14]:
A
A.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

<h3 style="color:#C5D8A4; background:#534340; border-radius:5px; font">Broadcasting and Vectorized</h3>

In [21]:
a = np.arange(4)

In [22]:
a

array([0, 1, 2, 3])

In [23]:
a+10

array([10, 11, 12, 13])

In [24]:
a*10

array([ 0, 10, 20, 30])

In [25]:
a*=100

In [26]:
a

array([  0, 100, 200, 300])

In [27]:
a+=100
a

array([100, 200, 300, 400])

In [28]:
b=np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [29]:
a+b

array([101, 202, 303, 404])

In [30]:
a*b

array([ 100,  400,  900, 1600])

<h3 style="color:#C5D8A4; background:#534340; border-radius:5px; font">Boolean Arrays</h3>

In [31]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [32]:
a[0],a[-1]

(0, 3)

In [33]:
a[[0,-1]]

array([0, 3])

In [34]:
a[[True,False,False,True]]

array([0, 3])

In [35]:
a[a>1]

array([2, 3])

In [36]:
a.mean()

1.5

In [37]:
a[~(a>a.mean())]

array([0, 1])

In [38]:
a[(a==0)|(a==1)]

array([0, 1])

In [39]:
A=np.random.randint(100,size=(3,4))

In [40]:
A

array([[ 8, 14, 35, 34],
       [42, 57, 99, 45],
       [85, 76, 74, 71]])

In [41]:
A>30

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [42]:
A[A>30]

array([35, 34, 42, 57, 99, 45, 85, 76, 74, 71])

In [43]:
zero_arr=np.zeros(10)
zero_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
ones_arr=np.ones(5)
ones_arr

array([1., 1., 1., 1., 1.])

In [45]:
linespace_arr=np.linspace(start=5,stop=10,num=5)
linespace_arr

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

<h3 style="color:#C5D8A4; background:#534340; border-radius:5px; font">Size of Objects in Memory</h3>

<h5 style="color:#95D1CC; background:#22577E; border-radius:5px; font">int, floats</h5>

In [46]:
#An integer in python is > 24bytes
sys.getsizeof(1)

28

In [47]:
#Longs are even longer
sys.getsizeof(10**100)

72

In [48]:
#Numpy size is much smaller
np.dtype(int).itemsize

4

In [49]:
#Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [50]:
np.dtype(float).itemsize

8

<h5 style="color:#95D1CC; background:#22577E; border-radius:5px; font">Lists are even larger</h5>

In [51]:
#A one element list
sys.getsizeof([1])

64

In [52]:
#An array of one element in numpy
np.array([1]).itemsize

4

In [53]:
#python list operation
l=list(range(1000000))
%time sum([x**2 for x in l])

CPU times: total: 234 ms
Wall time: 248 ms


333332833333500000

In [54]:
#numpy list operation
a=np.arange(1000000)
%time np.sum(a**2)

CPU times: total: 0 ns
Wall time: 1.99 ms


584144992

In [58]:
np_a=np.array([])
new  = np.append(np_a,456)
print(new)
    

[456.]


In [61]:
np.delete(new,0)

array([], dtype=float64)