```
1) Create a numpy array which contains the first 10 elements. Negate the elements between 4 to 7. Output should be - array([ 0, 1, 2, 3, 4, -5, -6, 7, 8, 9]).
```


In [2]:
import numpy as np

In [4]:

arr = np.array([0, 1, 2, 3, 4, -5, -6, 7, 8, 9])
arr[(4 < arr) & (arr < 7)] = -1
arr

array([ 0,  1,  2,  3,  4, -5, -6,  7,  8,  9])

```
2) A person is recording his weight everyday for 3 weeks. Create an array with average weight per weekend. Note that a week is starting from a monday. Weight of a person for 3 weeks-
array([72. , 71.85714286, 71.71428571, 71.57142857, 71.42857143,
71.28571429, 71.14285714, 71. , 70.85714286, 70.71428571,
70.57142857, 70.42857143, 70.28571429, 70.14285714, 70. ,
69.85714286, 69.71428571, 69.57142857, 69.42857143, 69.28571429,
69.14285714])
```


In [5]:
arr = np.array([72., 71.85714286, 71.71428571, 71.57142857, 71.42857143,
                71.28571429, 71.14285714, 71., 70.85714286, 70.71428571,
                70.57142857, 70.42857143, 70.28571429, 70.14285714, 70.,
                69.85714286, 69.71428571, 69.57142857, 69.42857143, 69.28571429,
                69.14285714])

```
3) Which of the following options is correct ? Condition - Add both the arrays and then multiply with
a. Fetch the 3rd element
a=np.array([2,10,12,20,55])
b=np.array([5,10,33,66,99])
```


In [9]:
a = np.array([2, 10, 12, 20, 55])
b = np.array([5, 10, 33, 66, 99])
((a+b)*a)[2]

540

```
4) What will be the output of the code ?
import numpy as np
a=np.array([9,8,7,1,3,1,2],ndim=3)
a
```


In [10]:
a = np.array([9, 8, 7, 1, 3, 1, 2], ndim=3)
a

TypeError: array() got an unexpected keyword argument 'ndim'

```
5) Find the pearson product- moment correlation coefficients by doing the reverse of numpy array1 with array2 ?
Given -
array1 = np.array([55,67,87,75,11])
array2 = np.array([32,22,11,15,99])
```


In [22]:
array1 = np.array([55, 67, 87, 75, 11])
array2 = np.array([32, 22, 11, 15, 99])
np.corrcoef(array2, array1)

array([[ 1.        , -0.98053117],
       [-0.98053117,  1.        ]])

```
6) What will be the output of the following code ?
import numpy as np
x = np.array([1,78,87,99])
y = np.array([37,45,55,23,43,56])
z = np.array([21,2,93,53,87,99])
x, y, z = np.ix_(x,y,z)
print(x)
```


In [23]:
x = np.array([1, 78, 87, 99])
y = np.array([37, 45, 55, 23, 43, 56])
z = np.array([21, 2, 93, 53, 87, 99])
x, y, z = np.ix_(x, y, z)
print(x)

[[[ 1]]

 [[78]]

 [[87]]

 [[99]]]


```
7) What is the total bytes consumed by the elements of the array?
a=np.array([23,45,56,78,100])
```


In [27]:
a = np.array([23, 45, 56, 78, 100])
a.nbytes

20

```
8) Which is the correct logic to convert a 1-D array to 2-D one-hot array?
a = np.array([2,7,5])
```


In [29]:
a = np.array([2, 7, 5])
b = np.zeros((a.size, a.max() + 1))
b[np.arange(a.size), a] = 1
b

array([[0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0.]])

```
9) Calculate the min by max for each row for a given numpy array
np.random.seed(10)
a = np.random.randint(2,12, [7,5])
```


In [49]:
np.random.seed(10)
a = np.random.randint(2, 12, [7, 5])
mi = np.min(a, axis=1)
ma = np.max(a, axis=1)
mi, ma

(array([2, 2, 2, 3, 3, 3, 4]), array([11, 11, 10, 10,  8, 11, 11]))

```
10) Correct logic to convert an array of arrays into a flat 1-D array ?
a=np.arange(5)
b=np.arange(5,8)
c=np.arange(8,13)
d = np.array([a,b,c])
```


In [ ]:
a = np.arange(5)
b = np.arange(5, 8)
c = np.arange(8, 13)
d = np.array([a, b, c])
np.array([a for arr in d for a in arr])
np.concatenate(d)

```
Correct logic to create rank for items in an array using numpy ?
Given -
np.random.seed(10)
a = np.random.randint(10, size=10)
print(a)
```


In [54]:
np.random.seed(10)
a = np.random.randint(10, size=10)
print(a.argsort())

45


In [57]:

x = np.random.randint(100)
print(x)

40


In [64]:
# 13) What will be the transpose of a matrix ?
x = np.array([[5, 7], [2, 3]])
np.transpose(a)
x

array([[5, 7],
       [2, 3]])

In [67]:
a = np.array([22, 33, 45, 67, 89, 11, 111, 23, 45])
a.min()

11