## Numpy Hands-On


In [5]:
import numpy as np

### 1. Create a numpy array with numpy.array module and with a data type integer and float.


In [13]:
np_float = np.array([], dtype=np.float32)
np_int = np.array([], dtype=np.int32)
np_float.dtype
np_int.dtype

dtype('int32')

### 2. Create numpy arrays that have zero, one, two, three, Four dimensions respectively. Also, print the shape and dimensions of the numpy arrays created above.


In [22]:

print(f'''
{
    np.ndim(np.array(0)),
    np.ndim(np.array([1])),
    np.ndim(np.array([[2]])),
    np.ndim(np.array([[[3]]])),
    np.ndim(np.array([[[[4],[5]]],[[[4],[5]]]]))
}
''')


(0, 1, 2, 3, 4)



#### 3. Create a 2x3, 3x3, and 4x4 identity matrix using numpy.


In [43]:
a2 = np.identity(2, dtype=np.int8),
a3 = np.identity(3, dtype=np.int8),
a4 = np.identity(4, dtype=np.int8)
a5 = np.eye(5)
print(a2, a3, a4, a5)

(array([[1, 0],
       [0, 1]], dtype=int8),) (array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8),) [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 4. Create a numpy array with shape 2x5 that has all the elements as zero.


In [57]:
np.zeros((2, 5), dtype=np.int8)
# help(np.zeros)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

### 5. Create a numpy array that has the shape 3x5 and all the elements are 5.


In [60]:
np.full((3, 5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

### 6. Create a numpy array with random integers in the range 0-100, and the sample size should be 25.


In [71]:
# np.linspace(0,100,25,dtype=np.int8).reshape(5,5)

array([[  0,   4,   8,  12,  16],
       [ 20,  25,  29,  33,  37],
       [ 41,  45,  50,  54,  58],
       [ 62,  66,  70,  75,  79],
       [ 83,  87,  91,  95, 100]], dtype=int8)

In [72]:
np.random.randint(0, 100, 25, dtype=np.int8).reshape(5, 5)

array([[38, 83, 58, 86, 39],
       [55, 28, 38, 25, 84],
       [64, 84, 76, 93,  8],
       [ 3, 64,  4, 55, 74],
       [70, 88, 29, 40, 39]])

### 7. Create a numpy array with a shape 3x3 that has all elements as 1.


In [74]:
np.ones((3, 3), dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

### 8. Create a numpy array in the shape 2x3 with random integers in the range 0-100. Reshape the array in the shape 3x2 and print the updated shape of the resultant array.


In [82]:
np.random.randint(0, 100, (2, 3)).reshape(3, 2).shape

(3, 2)

````
9. Create a random array, with the range 0-1000, with a size 50 and step 2. Perform the
following operations on the same.
a. Print the first ten elements of the array.
b. Print the last ten elements of the array
c. Print the elements from the indexes 10-25
d. Print the element at the index 22
e. Print the array using negative indexing.
f. Print the last ten elements of the array, using negative indexing.```
````


In [87]:
rand_arr = np.random.randint(0, 1000, 50)
rand_arr

array([ 78, 583, 696, 999, 970, 352, 459, 821, 716, 794, 277, 692, 345,
       213,  75,  83, 611, 721, 523, 340, 307, 485, 390, 606, 619, 702,
       488, 832, 940, 852, 971, 645, 249, 173, 178, 815, 159, 682, 612,
       856,   8, 600, 413, 462, 191, 408, 972, 707, 104, 890])

In [88]:
rand_arr[:10]

array([ 78, 583, 696, 999, 970, 352, 459, 821, 716, 794])

In [95]:
rand_arr[40:]

array([  8, 600, 413, 462, 191, 408, 972, 707, 104, 890])

In [91]:
rand_arr[10:26]

array([277, 692, 345, 213,  75,  83, 611, 721, 523, 340, 307, 485, 390,
       606, 619, 702])

In [92]:
rand_arr[22]

390

In [94]:
rand_arr[-len(rand_arr):]

array([ 78, 583, 696, 999, 970, 352, 459, 821, 716, 794, 277, 692, 345,
       213,  75,  83, 611, 721, 523, 340, 307, 485, 390, 606, 619, 702,
       488, 832, 940, 852, 971, 645, 249, 173, 178, 815, 159, 682, 612,
       856,   8, 600, 413, 462, 191, 408, 972, 707, 104, 890])

```
10. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
a. Insert the element 6 at the end of the array.
b. Insert the element 10 at the beginning of the array.
c. Insert the element 30, before 4.
d. Update the element 5 as 50.
e. Delete the element 50 in the updated array.
f. Create a function to search for the element 30.
g. Sort the array in ascending order.
```


In [97]:
sample_arr = np.array(range(1, 6))
sample_arr

array([1, 2, 3, 4, 5])

In [101]:
np.append(sample_arr, 6)

array([1, 2, 3, 4, 5, 6])

In [121]:
np.insert(sample_arr, np.where(sample_arr == 4)[0], 30)

array([ 1,  2,  3, 30,  4, 50])

In [115]:
sample_arr[sample_arr==5]=50
sample_arr

array([ 1,  2,  3,  4, 50])

In [116]:
np.delete(sample_arr,np.where(sample_arr==50))

array([1, 2, 3, 4])

In [130]:
# pos=np.where(sample_arr==30)
a=lambda arr,n:arr.tolist().index(n) if n in arr else f'Not in list'
a(sample_arr,30)

'Not in list'

In [118]:
np.sort(sample_arr)

array([ 1,  2,  3,  4, 50])

In [7]:
# flatten numpy array
arr=np.array([[1,2,3],[3,4,5]])
arr.ravel()


array([1, 2, 3, 3, 4, 5])