### Exercise 1
Consider the given Python list and follow the steps below:

L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]

Convert this Python list to NumPy array

Sort the array

Delete the 5th element from the array (Note: Python indexing starts from 0, so if we say the first element, Python will  take it as 0th element)

In [61]:
L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]

In [72]:
import numpy as np

#converting python list in array 
np_arr=np.array(L)

#sorting array
np_arr.sort()

#deleting 5th element from array
np_deleted = np.delete(np_arr,4)

np_deleted

array([ 2,  3,  7,  8, 12, 13, 22, 23, 25, 41, 46, 54])

Add 53 at the end of the list

Reshape it into a shape of (2, 7)

In [63]:
np_new=np.append(np_arr,53)

In [64]:
#reshaping array
np_new
arr_shape=(2,7)
np_new.reshape(arr_shape)

array([[ 2,  3,  7,  8, 10, 12, 13],
       [22, 23, 25, 41, 46, 54, 53]])

### Exercise 2
Select the correct option that will help you to get the value 13 from the array arr.

In [79]:
np_indexed_arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [80]:
np_indexed_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [83]:
#selecting element from array
np_indexed_arr[2,2]

13

In [84]:
np_indexed_arr[2][2]

13

In [85]:
single_row=np.arange(25)

In [86]:
single_row

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [111]:
single_row_reshaped=single_row.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [113]:
single_row_reshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [114]:
single_row_reshaped[:2,3:]

array([[3, 4],
       [8, 9]])

In [121]:
single_row_reshaped[1::2,0::2]

array([[ 5,  7,  9],
       [15, 17, 19]])